name: Publish PDF

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up LaTeX environment
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex

    - name: Build PDF
      run: |
        latexmk -pdf -interaction=nonstopmode -file-line-error -halt-on-error main.tex

    - name: Rename PDF
      run: |
        mv main.pdf Rapport_Projet_Integre.pdf

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload PDF
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: Rapport_Projet_Integre.pdf
        asset_name: Rapport_Projet_Integre.pdf
        asset_content_type: application/pdf
